# Generated by Django 6.1.1 on 2026-09-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID')),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.CharField(help_text='Street Address', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City Name', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='2-letter State Code', max_length=2)),
                ('rack_id', models.IntegerField(help_text='Rack ID')),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, help_text='Retail Price per Gallon in USD', max_digits=7)),
                ('latitude', models.FloatField(db_index=True, help_text='WGS84 Latitude')),
                ('longitude', models.FloatField(db_index=True, help_text='WGS84 Longitude')),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'indexes': [models.Index(fields=['state', 'city'], name='fuel_api_fu_state_4d6fd2_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_api_fu_latitud_8b84ad_idx')],
            },
        ),
    ]
